# Generated by Django 5.0 on 2024-06-19 07:03

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+0000000000', max_length=128, region=None, unique=True, verbose_name='Phone number'),
        ),
    ]
